EKF: Fix reporting of non position mode innovation test levels
PX4/PX4-ECL pull request #964
Opened 2021-01-19 10:17 UTC by priseborough

This change fixes a bug that allowed IMU gyro errors large enough to cause large tilt errors prior to start of aiding, to not result in large innovation test ratios. When only 2 IMU's are being used in a multi EKF setup, this results in the EKF selector not switching as the test ratio due to the diverging position stays a small number due to the large gate, eg:

![Screen Shot 2021-01-19 at 9 08 53 pm](https://user-images.githubusercontent.com/3596952/105019845-ae42aa00-5a9a-11eb-88e3-53b3401a3bca.png)

2021-01-19 10:18 UTC, priseborough commented
@bresch Can you please test on your setup and see if it resolves the issue. TXS

2021-01-19 16:40 UTC, bresch requested changes
Thanks, I'll test it

2021-01-19 16:40 UTC, bresch commented on EKF/control.cpp
> +			fuseHorizontalPosition(_ev_pos_innov, ev_pos_innov_gates, ev_pos_obs_var, _ev_pos_innov_var, _ev_pos_test_ratio, false);
```suggestion
			fuseHorizontalPosition(_ev_pos_innov, ev_pos_innov_gates, ev_pos_obs_var, _ev_pos_innov_var, _ev_pos_test_ratio);
```

2021-01-20 23:13 UTC, priseborough commented on EKF/control.cpp
> +			fuseHorizontalPosition(_ev_pos_innov, ev_pos_innov_gates, ev_pos_obs_var, _ev_pos_innov_var, _ev_pos_test_ratio, false);
Done

2021-01-20 23:14 UTC, priseborough commented on EKF/ekf.h
> +				    Vector3f &innov_var, Vector2f &test_ratiov, bool inhibit_gate);
Done

2021-01-20 23:14 UTC, priseborough commented on EKF/control.cpp
> +			fuseHorizontalPosition(_gps_pos_innov, gps_pos_innov_gates, gps_pos_obs_var, _gps_pos_innov_var, _gps_pos_test_ratio, false);
Done

2021-01-20 23:42 UTC, priseborough commented
I have done some testing in SITL  using 'make px4_sitl gazebo' with the following parameter customisations

EKF2_MULTI_IMU = 2
SYS_FAILURE_EN = 1

GPS was failed just after startup using 'failure gps off'

Then a large gyro bias offset was added by setting

CAL_GYRO0_XOFF = 0.5

Because the SITL model is reading 3 IMU's the triplex monitor algorithm was able to identify the failed gyro immediately, however what is important is that the reported test ratio for the affected EKF instances went to large values quickly.

![Screen Shot 2021-01-21 at 10 37 17 am](https://user-images.githubusercontent.com/3596952/105254216-24e3c280-5bd5-11eb-85c3-3973495a26c3.png)

2021-01-21 00:03 UTC, dagar commented
<img width="1019" alt="Screen Shot 2021-01-20 at 7 02 31 PM" src="https://user-images.githubusercontent.com/84712/105255695-12747500-5b52-11eb-8907-18c8e0b02026.png">


This is a question for the PX4-Autopilot ekf2selector, but should we stop automatically clearing the gyro faults every iteration? https://github.com/PX4/PX4-Autopilot/blob/9a066959d4c3e0f06bfd50a483c04051aa282f02/src/modules/ekf2/EKF2Selector.cpp#L119

2021-01-21 01:17 UTC, priseborough commented
I was able to test on a Pixhawk 4 board with 

EKF2_MULTI_IMU = 2
EKF2_MULTI_MAG = 2
SENS_IMU_MODE = 0
SENS_MAG_MODE = 0

EKF2_AID_MASK = 0

After rebooting and waiting for the alignment, CAL_GYRO0_XOFF was increased by 0.5 rad/sec and the primary instance changed rapidly as required.

![Screen Shot 2021-01-21 at 12 15 24 pm](https://user-images.githubusercontent.com/3596952/105260686-5adb7380-5be2-11eb-94b0-5820fac63a6d.png)

2021-01-21 08:40 UTC, bresch approved these changes

2021-01-21 09:55 UTC, merged

2021-01-21 10:03 UTC, priseborough commented
> <img alt="Screen Shot 2021-01-20 at 7 02 31 PM" width="1019" src="https://user-images.githubusercontent.com/84712/105255695-12747500-5b52-11eb-8907-18c8e0b02026.png">
> 
> This is a question for the PX4-Autopilot ekf2selector, but should we stop automatically clearing the gyro faults every iteration? https://github.com/PX4/PX4-Autopilot/blob/9a066959d4c3e0f06bfd50a483c04051aa282f02/src/modules/ekf2/EKF2Selector.cpp#L119

@dagar The lack of a persistence criteria is more of a loggoing issue given we switch immediately when _gyro_fault_detected goes true. We could wait  500msec before clearing, but unless there is a logging efficiency issue created by the current behaviour, it would be adding unnecessary code IMO.

2021-01-21 14:42 UTC, dagar commented
> @dagar The lack of a persistence criteria is more of a loggoing issue given we switch immediately when _gyro_fault_detected goes true. We could wait 500msec before clearing, but unless there is a logging efficiency issue created by the current behaviour, it would be adding unnecessary code IMO.

As long as it's only a logging issue I'll leave it alone. I was more concerned with unnecessarily clearing the gyro fault between ekf2 selector iterations with `sensors_status_status` not necessarily synchronized.