Allow RangeFinder fusion in vision height mode (Fix for #994)
PX4/PX4-ECL pull request #999
Opened 2021-04-01 20:27 UTC by ecmnet

Although `controlHeightSensorTimeouts()` switched to` rng_hgt` mode correctly as soon as an ev timeout happens, range finder height fusion is not performed as `rng_hgt` is not allowed if vision is the primary height source. This PR allows range finder height fusion even if vision is selected as primary height source.

Relates to https://github.com/PX4/PX4-ECL/pull/994

2021-04-01 20:43 UTC, dagar commented on EKF/control.cpp
> +		if (_control_status.flags.rng_hgt) {
Only fuse height if _range_sensor.isDataHealthy()?

2021-04-01 20:43 UTC, dagar commented on EKF/control.cpp
> +		if (_control_status.flags.rng_hgt) {
```suggestion
		if (_control_status.flags.rng_hgt && _range_sensor.isDataHealthy()) {
```

2021-04-24 14:12 UTC, ecmnet commented
@bresch Could you have a look? #994 does not work without this fix.

2021-04-24 17:53 UTC, mhkabir commented
A little late to the party here (missed #994 for a while), so please humor me. 

How does fallback from vision to range work, if there is an offset between the vision Z and rangefinder Z? Is the offset compensated for before starting range fusion?

I'm also wondering if would it be better to fall back to range-aided baro instead of pure rangefinder in case flying over ground with obstacles/non-flat ground.

2021-04-27 04:17 UTC, ecmnet commented
> A little late to the party here (missed #994 for a while), so please humor me.
> 
> How does fallback from vision to range work if there is an offset between the vision Z and rangefinder Z? Is the offset compensated for before starting range fusion?
> 
> I'm also wondering if would it be better to fall back to range-aided baro instead of pure rangefinder in case flying over ground with obstacles/non-flat ground.

The offset is compensated in #994 already. Purpose of the fallback is to support vision reset cycles / drop outs (e.g. direct sun, etc.) - therefore the assumption of a flat ground seems to be sufficient.

2021-04-27 07:26 UTC, mhkabir approved these changes

2021-04-28 05:38 UTC, mhkabir commented on EKF/control.cpp
> +		if (_control_status.flags.rng_hgt && _range_sensor.isDataHealthy()) {
Can you replace 1082 - 1095 with this block?
```
               if (_control_status.flags.ev_hgt && _ev_data_ready) {
                       fuse_height = true;
               } else if (_control_status.flags.rng_hgt && _range_sensor.isDataHealthy()) {
                       fuse_height = true;
               } else if (_control_status.flags.baro_hgt && _baro_data_ready && !_baro_hgt_faulty) {
                        fuse_height = true;
               }

```

This groups the statements together like for GPS (few lines above), and adds a check for `_ev_data_ready` which fixes the issue you saw here https://github.com/PX4/PX4-ECL/pull/994#discussion_r621816867.

After that you can also revert the change you made on line 792 in #994, and timeouts will work as designed.

2021-04-28 05:38 UTC, mhkabir requested changes
See inline comment

2021-04-30 16:16 UTC, mhkabir approved these changes
Perfect! Tested via backport and works.

2021-04-30 18:17 UTC, merged